2023-03-19 17:01:28,579 DEBUG decors.py Была вызвана функция arg_parser c параметрами () , {}. Вызов из модуля __main__
2023-03-19 17:01:28,582 INFO server.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-03-19 17:01:52,446 INFO server.py Установлено соединение с ПК ('127.0.0.1', 51269)
2023-03-19 17:01:52,447 DEBUG decors.py Была вызвана функция get_message c параметрами (<socket.socket fd=528, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51269)>,) , {}. Вызов из модуля common.utils
2023-03-19 17:01:52,448 DEBUG server.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1679234512.446808, 'user': {'account_name': 'asd'}}
2023-03-19 17:01:52,448 DEBUG decors.py Была вызвана функция send_message c параметрами (<socket.socket fd=528, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51269)>, {'response': 200}) , {}. Вызов из модуля common.utils
2023-03-19 17:02:00,613 DEBUG decors.py Была вызвана функция get_message c параметрами (<socket.socket fd=528, family=2, type=1, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51269)>,) , {}. Вызов из модуля common.utils
2023-03-19 17:02:00,613 DEBUG server.py Разбор сообщения от клиента : {'action': 'message', 'from': 'asd', 'to': '1', 'time': 1679234520.2367492, 'mess_text': '111'}
2023-03-19 17:02:00,613 ERROR server.py Пользователь 1 не зарегистрирован на сервере, отправка сообщения невозможна.
